Resources:
  # MyLambdaFunction:
  #   Type: 'AWS::Serverless::Function'
  #   Properties:
  #     Handler: index.handler
  #     Runtime: nodejs12.x
  #     CodeUri: .
  #     MemorySize: 128
  #     Timeout: 30
  #     Environment:
  #       Variables:
  #         REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpointAddress
  #     Events:
  #       MyApi:
  #         Type: Api
  #         Properties:
  #           Path: /myendpoint
  #           Method: get

  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache Redis
      SubnetIds:
        - subnet-02c217f126c0ce1d5
      CodeUri: .

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: vpc-066e6a637e37f2752
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          DestinationSecurityGroupId: !GetAtt MyElasticacheRedis.SecurityGroupId
      CodeUri: .
